alias: Lancer filtration piscine matin
trigger:
  - platform: time
    at: "08:00:00"
action:
  - service: piscine_manager.start_filtration
    data:
      pompe: switch.pompe_piscine
      mode: "filtration_normale"
