start_cycle:
  description: "Démarre un cycle de filtration manuel"
  fields:
    entity_id:
      description: "L'entité de la pompe"
      example: "switch.pompe"
      selector:
        entity:
          domain: switch